//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Taxi.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Taxi : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Taxi()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Taxi"",
    ""maps"": [
        {
            ""name"": ""TaxiIranyitas"",
            ""id"": ""c36c65ea-d00e-4faf-b7db-70a691db1fa3"",
            ""actions"": [
                {
                    ""name"": ""Iranyitas"",
                    ""type"": ""Button"",
                    ""id"": ""9fcd1aab-a7e4-45e3-bfa6-57fdc81ebd51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fek"",
                    ""type"": ""Button"",
                    ""id"": ""295ce6b7-3c5f-4ee6-990f-a9cdd03986ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""JobbEsBal"",
                    ""id"": ""aa0dc48a-6697-4852-a951-61d886609756"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Iranyitas"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4fbdb3b4-7a73-4f16-8014-6b152ca2d9fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Iranyitas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d9c8dcbe-dee7-4626-ae04-cbfca63a004e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Iranyitas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e937c3ac-a0ab-40ec-ac1f-fffcb180b4c9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fek"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Manu"",
            ""id"": ""693808a6-5e35-4750-bc4e-2d67d8a16f07"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""8e4fabaa-4da3-461b-8fb5-f2ff5ec03fa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""796bb6fd-32d3-4c62-b314-7e26d3f19e43"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""799fb841-cc4c-4ce3-89ff-bf7de50b4d4b"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29971a1-9ca1-4b1a-a67f-80c5078510d6"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TaxiIranyitas
        m_TaxiIranyitas = asset.FindActionMap("TaxiIranyitas", throwIfNotFound: true);
        m_TaxiIranyitas_Iranyitas = m_TaxiIranyitas.FindAction("Iranyitas", throwIfNotFound: true);
        m_TaxiIranyitas_Fek = m_TaxiIranyitas.FindAction("Fek", throwIfNotFound: true);
        // Manu
        m_Manu = asset.FindActionMap("Manu", throwIfNotFound: true);
        m_Manu_Menu = m_Manu.FindAction("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TaxiIranyitas
    private readonly InputActionMap m_TaxiIranyitas;
    private ITaxiIranyitasActions m_TaxiIranyitasActionsCallbackInterface;
    private readonly InputAction m_TaxiIranyitas_Iranyitas;
    private readonly InputAction m_TaxiIranyitas_Fek;
    public struct TaxiIranyitasActions
    {
        private @Taxi m_Wrapper;
        public TaxiIranyitasActions(@Taxi wrapper) { m_Wrapper = wrapper; }
        public InputAction @Iranyitas => m_Wrapper.m_TaxiIranyitas_Iranyitas;
        public InputAction @Fek => m_Wrapper.m_TaxiIranyitas_Fek;
        public InputActionMap Get() { return m_Wrapper.m_TaxiIranyitas; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TaxiIranyitasActions set) { return set.Get(); }
        public void SetCallbacks(ITaxiIranyitasActions instance)
        {
            if (m_Wrapper.m_TaxiIranyitasActionsCallbackInterface != null)
            {
                @Iranyitas.started -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnIranyitas;
                @Iranyitas.performed -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnIranyitas;
                @Iranyitas.canceled -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnIranyitas;
                @Fek.started -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnFek;
                @Fek.performed -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnFek;
                @Fek.canceled -= m_Wrapper.m_TaxiIranyitasActionsCallbackInterface.OnFek;
            }
            m_Wrapper.m_TaxiIranyitasActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Iranyitas.started += instance.OnIranyitas;
                @Iranyitas.performed += instance.OnIranyitas;
                @Iranyitas.canceled += instance.OnIranyitas;
                @Fek.started += instance.OnFek;
                @Fek.performed += instance.OnFek;
                @Fek.canceled += instance.OnFek;
            }
        }
    }
    public TaxiIranyitasActions @TaxiIranyitas => new TaxiIranyitasActions(this);

    // Manu
    private readonly InputActionMap m_Manu;
    private IManuActions m_ManuActionsCallbackInterface;
    private readonly InputAction m_Manu_Menu;
    public struct ManuActions
    {
        private @Taxi m_Wrapper;
        public ManuActions(@Taxi wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_Manu_Menu;
        public InputActionMap Get() { return m_Wrapper.m_Manu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManuActions set) { return set.Get(); }
        public void SetCallbacks(IManuActions instance)
        {
            if (m_Wrapper.m_ManuActionsCallbackInterface != null)
            {
                @Menu.started -= m_Wrapper.m_ManuActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_ManuActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_ManuActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_ManuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public ManuActions @Manu => new ManuActions(this);
    public interface ITaxiIranyitasActions
    {
        void OnIranyitas(InputAction.CallbackContext context);
        void OnFek(InputAction.CallbackContext context);
    }
    public interface IManuActions
    {
        void OnMenu(InputAction.CallbackContext context);
    }
}
